#' @title The mutation summary
#' @description
#' Map mutation information based on the maftools package.
#'
#' @param mutation.obj an MAF object generated by read.maf, defaults to TCGA-MC3 project data, the user-defined dataset need to include at least Hugo_Symbol, Tumor_Sample_Barcode, Variant_Classification columns.
#' @param plotmafSummary logical, defaults to TRUE, plots maf summary.
#' @param plotTiTv logical, defaults to TRUE，plot Transition and Trasnversion ratios. Takes results generated from titv and plots the Ti/Tv ratios and contributions of 6 mutational conversion classes in each sample.
#'
#' @importFrom maftools plotmafSummary plotTiTv
#' @importFrom utils read.delim
#'
#' @return
#'
#' @export
#'
#' @examples
mutsummary <- function(mutation.obj,plotmafSummary,plotTiTv){
  if(plotmafSummary==T){
    plotmafSummary(mutation.obj)
  }
  if(plotTiTv==T){
    TCGA_mutation.titv = titv(maf = mutation.obj, plot = FALSE, useSyn = TRUE)
    plotTiTv(res = TCGA_mutation.titv)
  }
}
