#' @title Draw an oncoplot
#'
#' @param mutation.obj an MAF object generated by read.maf, defaults to TCGA-MC3 project data, the user-defined dataset need to include at least Hugo_Symbol, Tumor_Sample_Barcode, Variant_Classification columns.
#' @param LR_data A dataset with at least ligand/receptor columns of data. The default is the TICC and Omnipath datasets.
#' @param top_ligand how many top ligand drawn. defaults to 10.
#' @param top_receptor how many top receptor drawn. defaults to 10.
#' @param minMut
#' @param genes
#' @param altered
#' @param drawRowBar
#' @param drawColBar
#' @param leftBarData
#' @param leftBarLims
#' @param leftBarVline
#' @param leftBarVlineCol
#' @param rightBarData
#' @param rightBarLims
#' @param rightBarVline
#' @param rightBarVlineCol
#' @param topBarData
#' @param topBarLims
#' @param topBarHline
#' @param topBarHlineCol
#' @param logColBar
#' @param includeColBarCN
#' @param clinicalFeatures
#' @param annotationColor
#' @param annotationDat
#' @param pathways
#' @param topPathways
#' @param path_order
#' @param selectedPathways
#' @param collapsePathway
#' @param pwLineCol
#' @param pwLineWd
#' @param draw_titv
#' @param titv_col
#' @param showTumorSampleBarcodes
#' @param tsbToPIDs
#' @param barcode_mar
#' @param barcodeSrt
#' @param gene_mar
#' @param anno_height
#' @param legend_height
#' @param sortByAnnotation
#' @param groupAnnotationBySize
#' @param annotationOrder
#' @param sortByMutation
#' @param keepGeneOrder
#' @param GeneOrderSort
#' @param sampleOrder
#' @param additionalFeature
#' @param additionalFeaturePch
#' @param additionalFeatureCol
#' @param additionalFeatureCex
#' @param genesToIgnore
#' @param removeNonMutated
#' @param fill
#' @param cohortSize
#' @param colors
#' @param cBioPortal
#' @param bgCol
#' @param borderCol
#' @param annoBorderCol
#' @param numericAnnoCol
#' @param drawBox
#' @param fontSize
#' @param SampleNamefontSize
#' @param titleFontSize
#' @param legendFontSize
#' @param annotationFontSize
#' @param sepwd_genes
#' @param sepwd_samples
#' @param writeMatrix
#' @param colbar_pathway
#' @param showTitle
#' @param titleText
#' @param showPct
#'
#' @importFrom maftools oncoplot
#'
#' @return
#' @export
#'
#' @examples
oncoplot <- function(mutation.obj,
                     LR_data,
                     top_ligand=10,
                     top_receptor=10,
                     minMut = NULL,
                     genes = NULL,
                     altered = FALSE,
                     drawRowBar = TRUE,
                     drawColBar = TRUE,
                     leftBarData = NULL,
                     leftBarLims = NULL,
                     leftBarVline = NULL,
                     leftBarVlineCol = "gray70",
                     rightBarData = NULL,
                     rightBarLims = NULL,
                     rightBarVline = NULL,
                     rightBarVlineCol = "gray70",
                     topBarData = NULL,
                     topBarLims = NULL,
                     topBarHline = NULL,
                     topBarHlineCol = "gray70",
                     logColBar = FALSE,
                     includeColBarCN = TRUE,
                     clinicalFeatures = NULL,
                     annotationColor = NULL,
                     annotationDat = NULL,
                     pathways = NULL,
                     topPathways = 3,
                     path_order = NULL,
                     selectedPathways = NULL,
                     collapsePathway = FALSE,
                     pwLineCol = "#535c68",
                     pwLineWd = 1,
                     draw_titv = FALSE,
                     titv_col = NULL,
                     showTumorSampleBarcodes = FALSE,
                     tsbToPIDs = NULL,
                     barcode_mar = 4,
                     barcodeSrt = 90,
                     gene_mar = 5,
                     anno_height = 1,
                     legend_height = 4,
                     sortByAnnotation = FALSE,
                     groupAnnotationBySize = TRUE,
                     annotationOrder = NULL,
                     sortByMutation = FALSE,
                     keepGeneOrder = FALSE,
                     GeneOrderSort = TRUE,
                     sampleOrder = NULL,
                     additionalFeature = NULL,
                     additionalFeaturePch = 20,
                     additionalFeatureCol = "gray70",
                     additionalFeatureCex = 0.9,
                     genesToIgnore = NULL,
                     removeNonMutated = FALSE,
                     fill = TRUE,
                     cohortSize = NULL,
                     colors = NULL,
                     cBioPortal = FALSE,
                     bgCol = "#CCCCCC",
                     borderCol = "white",
                     annoBorderCol = NA,
                     numericAnnoCol = NULL,
                     drawBox = FALSE,
                     fontSize = 0.8,
                     SampleNamefontSize = 1,
                     titleFontSize = 1.5,
                     legendFontSize = 1.2,
                     annotationFontSize = 1.2,
                     sepwd_genes = 0.5,
                     sepwd_samples = 0.25,
                     writeMatrix = FALSE,
                     colbar_pathway = FALSE,
                     showTitle = TRUE,
                     titleText = NULL,
                     showPct = TRUE){
  ligand <- unique(L_R_data$ligand)
  receptor <- unique(L_R_data$receptor)
  ligand1 <- data.frame(ligand)
  colnames(ligand1) <- c("Hugo_Symbol")
  receptor1 <- data.frame(receptor)
  colnames(receptor1) <- c("Hugo_Symbol")
  mutation.obj_ligand <- merge(ligand1,mutation.obj,by="Hugo_Symbol")
  mutation.obj_receptor <- merge(receptor1,mutation.obj,by="Hugo_Symbol")
  if(is.null(top_ligand)!=TRUE){
    mutation.obj_ligand_data = read.maf(maf = mutation.obj_ligand,
                                        vc_nonSyn=names(tail(sort(table(mutation.obj_ligand$Variant_Classification)))))
    maftools::oncoplot(mutation.obj_ligand_data,top=top_ligand,
                       minMut,
                       genes,
                       altered,
                       drawRowBar,
                       drawColBar,
                       leftBarData,
                       leftBarLims,
                       leftBarVline,
                       leftBarVlineCol,
                       rightBarData,
                       rightBarLims,
                       rightBarVline,
                       rightBarVlineCol,
                       topBarData,
                       topBarLims,
                       topBarHline,
                       topBarHlineCol,
                       logColBar,
                       includeColBarCN,
                       clinicalFeatures,
                       annotationColor,
                       annotationDat,
                       pathways,
                       topPathways,
                       path_order,
                       selectedPathways,
                       collapsePathway,
                       pwLineCol,
                       pwLineWd,
                       draw_titv,
                       titv_col,
                       showTumorSampleBarcodes,
                       tsbToPIDs,
                       barcode_mar,
                       barcodeSrt,
                       gene_mar,
                       anno_height,
                       legend_height,
                       sortByAnnotation,
                       groupAnnotationBySize,
                       annotationOrder,
                       sortByMutation,
                       keepGeneOrder,
                       GeneOrderSort,
                       sampleOrder,
                       additionalFeature,
                       additionalFeaturePch,
                       additionalFeatureCol,
                       additionalFeatureCex,
                       genesToIgnore,
                       removeNonMutated,
                       fill,
                       cohortSize,
                       colors,
                       cBioPortal,
                       bgCol,
                       borderCol,
                       annoBorderCol,
                       numericAnnoCol,
                       drawBox,
                       fontSize,
                       SampleNamefontSize,
                       titleFontSize,
                       legendFontSize,
                       annotationFontSize,
                       sepwd_genes,
                       sepwd_samples,
                       writeMatrix,
                       colbar_pathway,
                       showTitle,
                       titleText,
                       showPct)
  }
  if(is.null(top_receptor)!=TRUE){
    mutation.obj_receptor_data = read.maf(maf = mutation.obj_receptor,
                                        vc_nonSyn=names(tail(sort(table(mutation.obj_receptor$Variant_Classification)))))
    maftools::oncoplot(mutation.obj_receptor_data,top=top_receptor,
                       minMut,
                       genes,
                       altered,
                       drawRowBar,
                       drawColBar,
                       leftBarData,
                       leftBarLims,
                       leftBarVline,
                       leftBarVlineCol,
                       rightBarData,
                       rightBarLims,
                       rightBarVline,
                       rightBarVlineCol,
                       topBarData,
                       topBarLims,
                       topBarHline,
                       topBarHlineCol,
                       logColBar,
                       includeColBarCN,
                       clinicalFeatures,
                       annotationColor,
                       annotationDat,
                       pathways,
                       topPathways,
                       path_order,
                       selectedPathways,
                       collapsePathway,
                       pwLineCol,
                       pwLineWd,
                       draw_titv,
                       titv_col,
                       showTumorSampleBarcodes,
                       tsbToPIDs,
                       barcode_mar,
                       barcodeSrt,
                       gene_mar,
                       anno_height,
                       legend_height,
                       sortByAnnotation,
                       groupAnnotationBySize,
                       annotationOrder,
                       sortByMutation,
                       keepGeneOrder,
                       GeneOrderSort,
                       sampleOrder,
                       additionalFeature,
                       additionalFeaturePch,
                       additionalFeatureCol,
                       additionalFeatureCex,
                       genesToIgnore,
                       removeNonMutated,
                       fill,
                       cohortSize,
                       colors,
                       cBioPortal,
                       bgCol,
                       borderCol,
                       annoBorderCol,
                       numericAnnoCol,
                       drawBox,
                       fontSize,
                       SampleNamefontSize,
                       titleFontSize,
                       legendFontSize,
                       annotationFontSize,
                       sepwd_genes,
                       sepwd_samples,
                       writeMatrix,
                       colbar_pathway,
                       showTitle,
                       titleText,
                       showPct)
  }
}
